# Header
## menu:
##   Home: /
##   Location: /location
##   News: /news
##   About us: /about-us
##   Bahn: /bahn
##   Werkstatt: /werkstatt
##   Impressum: /impressum
menu:
  Home: /
  Clubraum: /clubraum
  ## "&Uuml;ber uns": /ueber-uns
  Eisenbahn: /bahn
  Modellbau: /modellbau
  ## Schiffe: /schiff
  Werkstatt: /werkstatt
  Impressum: /impressum
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
